server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker containers logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|(?P<image_name>(?:[^|]*))\|(?P<image_id>(?:[^|]*))\|(?P<container_id>(?:[^|]*))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
          image_name:
          image_id:
          container_id:
      - output:
          source: output

  # System logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog

  # Application logs (for lowcode platform)
  - job_name: lowcode-portal
    static_configs:
      - targets:
          - localhost
        labels:
          job: lowcode-portal
          service: frontend
          __path__: /var/log/lowcode-portal/*.log

  - job_name: lowcode-portal-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: lowcode-portal-service
          service: backend
          __path__: /var/log/lowcode-portal-service/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp:
            level:
            message:
            context:
            userId:
            type:
            service:
            stack:
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          context:
          type: