networks:
  lowcode-network:
    external: true

volumes:
  redis_data:
  redis_config:

services:
  redis:
    image: redis:7-alpine
    container_name: lowcode-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - lowcode-network
    environment:
      - REDIS_PASSWORD=lowcode_redis_2024
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: lowcode-redis-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:lowcode-redis:6379
      - REDIS_PASSWORD=lowcode_redis_2024
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123
    networks:
      - lowcode-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Insight (Alternative UI - more advanced)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: lowcode-redis-insight
    restart: unless-stopped
    ports:
      - "8082:8001"
    volumes:
      - redis_config:/db
    networks:
      - lowcode-network
    depends_on:
      - redis
    environment:
      - RIPORT=8001
    profiles:
      - insight