version: '3.8'

services:
  postgresql:
    image: postgres:15-alpine
    container_name: ton-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: tonlowcode
      POSTGRES_USER: tonuser
      POSTGRES_PASSWORD: tonpassword123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - ton-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tonuser -d tonlowcode"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ton-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tonlowcode.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - ton-network
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  postgresql_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ton-network:
    driver: bridge
    external: false