version: '3.8'

networks:
  lowcode-network:
    external: true

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgres_data:

services:
  sonarqube-db:
    image: postgres:15-alpine
    container_name: lowcode-sonarqube-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube_password_2024
      POSTGRES_DB: sonarqubedb
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    networks:
      - lowcode-network
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonarqube -d sonarqubedb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  sonarqube:
    image: sonarqube:10.4-community
    container_name: lowcode-sonarqube
    restart: unless-stopped
    depends_on:
      sonarqube-db:
        condition: service_healthy
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube.properties:/opt/sonarqube/conf/sonar.properties:ro
    environment:
      # Database Configuration
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqubedb
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube_password_2024
      
      # JVM Options
      SONAR_CE_JAVAOPTS: "-Xmx2g -Xms128m -XX:+HeapDumpOnOutOfMemoryError"
      SONAR_WEB_JAVAOPTS: "-Xmx1g -Xms128m -XX:+HeapDumpOnOutOfMemoryError"
      
      # System Configuration
      SONAR_WEB_HOST: 0.0.0.0
      SONAR_WEB_PORT: 9000
      SONAR_WEB_CONTEXT: /
      
      # Search Configuration
      SONAR_SEARCH_JAVAOPTS: "-Xmx1g -Xms1g -XX:MaxDirectMemorySize=256m -XX:+HeapDumpOnOutOfMemoryError"
      
      # Security
      SONAR_SECURITY_REALM: 
      SONAR_AUTHENTICATOR_DOWNCASE: true
      
      # Web Server
      SONAR_WEB_SESSION_TIMEOUT_IN_MINUTES: 60
      
    networks:
      - lowcode-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/api/system/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    sysctls:
      - vm.max_map_count=524288
      - fs.file-max=131072

  # SonarQube Scanner CLI (for manual scans)
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: lowcode-sonar-scanner
    volumes:
      - ../..:/usr/src:ro  # Mount project root as read-only
      - ./scanner-work:/tmp/scanner-work
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_LOGIN: admin
      SONAR_PASSWORD: admin123  # Default, change after first login
    networks:
      - lowcode-network
    depends_on:
      - sonarqube
    profiles:
      - scanner
    command: tail -f /dev/null  # Keep container running for manual scans

  # PostgreSQL Admin (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lowcode-sonarqube-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lowcode.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json:ro
    networks:
      - lowcode-network
    depends_on:
      - sonarqube-db
    profiles:
      - pgadmin
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3